version: "3"

networks:
  forgejo:
    external: false

services:
  forgejo_server:
    build: .
    image: nico-labs/forgejo_server:1.0
    container_name: forgejo_server
    hostname: forgejo_server
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - forgejo
    volumes:
      - ./gitea/data:/app/data
      - ./gitea/custom:/app/custom
      - ./gitea/log:/app/log
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"
  registry: 
    restart: always
    image: registry:2
    ports:
      - 5000:5000
