version: "3"
services:
  act_runner:
    build: .
    image: nimo_labs/act_runner:1.0.0
    container_name: act_runner
    network_mode: host 
    environment:
      - FORGEJO_IP=
      - FORGEJO_PORT=3000 #default
      - PROTOCOL=HTTPS #HTTP or HTTP
      - TOKEN=<enter token here>
      - LABELS=ubuntu-docker:docker://ubuntu-docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /path/to/act_runner:/act_runner
    restart: unless-stopped
